package mob.sdk.networking;

public enum TransactionType {
    BATTLE_REQUEST,
    BATTLE_REQUEST_INVALID,
    BATTLE_RESULT,
    CARD_REQUEST,
    CARD_REQUEST_INVALID,
    CARD_RESULT,
    RANDOM_CARD_REQUEST,
    RANDOM_CARD_RESULT
}
